### ISSUE TITLE
EUREX 예탁금및통합잔고조회(CEXAQ31200) 실행중에 에러 메세지 

### ISSUE THREAD

**Issue by kimtaeduck** [whitehwarang/eBREST#1]
EUREX 예탁금및통합잔고조회(CEXAQ31200) 실행중 에러 메세지에 아래 코드로 임시 대응하였지만 버그(?) 잡아주세요....
TypeError: unsupported operand type(s) for +: 'dict' and 'dict' 

async def rq_tr(session:ClientSession, tr_inst:BaseTR) -> dict:
    ---  중략 ---
    # 연속조회 루틴
    while rp['header'].get('tr_cont') == 'Y':
      ---  중략 ---
        # append re-requested data to the previously one.
        for sub_outblock_nm in _outblock_nms:
            if sub_outblock_nm == _main_outblock_nm: continue
    -->      `body[sub_outblock_nm] = rp['body'][sub_outblock_nm] + body[sub_outblock_nm]`
   
   ==>  if isinstance(body[sub_outblock_nm], list):
                body[sub_outblock_nm].extend(rp['body'][sub_outblock_nm])
            else:
                body[sub_outblock_nm].update(rp['body'][sub_outblock_nm])

**Comment by whitehwarang** [comment]
ㅇ 버그 리포트 감사합니다.
ㅇ (코드 수정) 아래 LINE A 다음에 LINE B를 추가하였습니다.
LINE A : if sub_outblock_nm == _main_outblock_nm: continue
LINE B : if isinstance(rp['body'][sub_outblock_nm], dict): continue

ㅇ (수정 이유) OutBlock이 복수개인 경우 첫번째 OutBlock만 dict타입이고 나머지는 list타입인 줄 알았는데, 그게 아니었네요. OutBlock이 dict 타입인 경우는 연속조회해도 해당 OutBlock의 데이터가 동일할 것이므로, dict타입인 경우는 스킵하도록 처리하였습니다.

**Comment by whitehwarang** [comment]
ㅇ 버그 리포트 감사합니다.
ㅇ (코드 수정)  해당 부분을 아래와 같이 변경하였습니다.
        # append re-requested list-type data to previously requested one.
        for sub_outblock_nm in _outblock_nms:
            if isinstance(rp['body'][sub_outblock_nm], list): 
                body[sub_outblock_nm] = rp['body'][sub_outblock_nm] + body[sub_outblock_nm]
ㅇ (수정 이유) 
 - OutBlock이 복수개인 경우 첫번째 OutBlock만 dict타입이고 나머지는 list타입인 줄 알았는데, 그게 아니었네요. 
 - dict타입인 경우는 스킵하고 list타입인 경우만 처리하도록 코드 변경하였습니다. 
 - OutBlockn이 dict 타입인 경우는 연속조회해도 해당 OutBlockn의 데이터가 직전조회와 동일할 것으로 가정한 것입니다.
